### ISSUE TITLE
Excessively large screenshots on homepage

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/cli#43]
The scaling on large screens for product screenshots is very large on app.r2c.dev. Could we make them smaller to distract less from login / sign-up boxes?

![image](https://user-images.githubusercontent.com/605906/58136765-2d0b8380-7be4-11e9-8e9a-6b03ed5d1ec9.png)

**Comment by ulziibay** [comment]
@dan5382: can you answer this question?

**Comment by dlukeomalley** [comment]
@dan5382 and @tnarla tracking.

**Comment by deifactor** [comment]
It seems like the root cause here is that the image is a background div as opposed to an actual image element, and that interacts badly with viewing the site on extremely wide monitors. I think it makes sense to just change it to an image, since we're not doing anything that makes it semantically a background.

**Comment by ulziibay** [comment]
There is design of the home page!

**Comment by ulziibay** [comment]
This is done!
